# app/config/schema.yml
# Geo-API
annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ApiPlatformCoreAnnotationGenerator

types: # The list of type to generated (a PHP entity class by type will be generated)

  Flight:
    parent: false
    properties:
      additionalType: ~
      arrivalAirport: { range: Airport }
      departureAirport: { range: Airport }
      departureTime: ~
      arrivalTime: ~
      provider: { range: Text }
      potentialAction: {range: Action}
  Airport:
    parent: false
    properties:
      iataCode:
        unique: true
      address: { range: PostalAddress }
  PostalAddress:
    parent: false
    properties:
      addressCountry:
        range: Text
      addressLocality: ~
      addressRegion: ~
      postalCode: ~
      streetAddress: ~
  Offer:
    parent: false
    properties:
      priceCurrency: ~
      itemOffered: { range: Flight }
      price: {
        range: Number }
      seller: { range: Text }
